# Generated by Django 4.2.20 on 2025-04-06 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('monday_open', models.TimeField(default='09:00:00')),
                ('monday_close', models.TimeField(default='12:00:00')),
                ('tuesday_open', models.TimeField(default='09:00:00')),
                ('tuesday_close', models.TimeField(default='21:00:00')),
                ('wednesday_open', models.TimeField(default='09:00:00')),
                ('wednesday_close', models.TimeField(default='21:00:00')),
                ('thursday_open', models.TimeField(default='09:00:00')),
                ('thursday_close', models.TimeField(default='21:00:00')),
                ('friday_open', models.TimeField(default='09:00:00')),
                ('friday_close', models.TimeField(default='21:00:00')),
                ('saturday_open', models.TimeField(default='09:00:00')),
                ('saturday_close', models.TimeField(default='21:00:00')),
                ('sunday_open', models.TimeField(default='09:00:00')),
                ('sunday_close', models.TimeField(default='21:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('delivery_address', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('parameter_1', models.CharField(blank=True, max_length=255, verbose_name='Параметр 1')),
                ('parameter_2', models.CharField(blank=True, max_length=255, verbose_name='Параметр 2')),
                ('parameter_3', models.CharField(blank=True, max_length=255, verbose_name='Параметр 3')),
                ('parameter_4', models.CharField(blank=True, max_length=255, verbose_name='Параметр 4')),
                ('parameter_5', models.CharField(blank=True, max_length=255, verbose_name='Параметр 5')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Артикул')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество в наличии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
