# Generated by Django 4.2.20 on 2025-04-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_orderproduct_order_products_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cvv',
            field=models.CharField(max_length=3, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Оформлен'), ('on assembly', 'На сборке'), ('on the way', 'В пути'), ('ready for pickup', 'Готов к выдаче'), ('handed over to the courier', 'Передан курьеру')], default='placed', max_length=50),
        ),
    ]
