# Generated by Django 4.2.20 on 2025-05-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_productparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_mah', models.PositiveIntegerField(unique=True, verbose_name='Емкость аккумулятора (мАч)')),
            ],
        ),
        migrations.CreateModel(
            name='CameraSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_mp', models.PositiveIntegerField(unique=True, verbose_name='Камера (Мп)')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Wired', 'Проводные'), ('Wireless', 'Беспроводные')], max_length=20, unique=True, verbose_name='Тип подключения')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Разъем для подключения')),
            ],
        ),
        migrations.CreateModel(
            name='CoreCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(unique=True, verbose_name='Количество ядер')),
            ],
        ),
        migrations.CreateModel(
            name='CPUFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_hz', models.PositiveIntegerField(unique=True, verbose_name='Тактовая частота процессора (Гц)')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_gb', models.PositiveIntegerField(unique=True, verbose_name='Память (GB)')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип ОС')),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Процессор')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_gb', models.PositiveIntegerField(unique=True, verbose_name='ОЗУ (GB)')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenDiagonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_inch', models.DecimalField(decimal_places=1, max_digits=4, unique=True, verbose_name='Диагональ экрана (дюймы)')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='parameter_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parameter_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parameter_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parameter_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parameter_5',
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Средний рейтинг'),
        ),
        migrations.DeleteModel(
            name='ProductParameter',
        ),
        migrations.AddField(
            model_name='product',
            name='battery_capacity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.batterycapacity', verbose_name='Емкость аккумулятора (мАч)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='connection_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.connectiontype', verbose_name='Тип подключения'),
        ),
        migrations.AddField(
            model_name='product',
            name='connector_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.connectortype', verbose_name='Разъем для подключения'),
        ),
        migrations.AddField(
            model_name='product',
            name='core_count',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.corecount', verbose_name='Количество ядер'),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu_frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cpufrequency', verbose_name='Тактовая частота процессора (Гц)'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_camera', to='accounts.cameraspec', verbose_name='Фронтальная камера (Мп)'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_camera', to='accounts.cameraspec', verbose_name='Основная камера (Мп)'),
        ),
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.memory', verbose_name='Память (GB)'),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.operatingsystem', verbose_name='Тип ОС'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.processor', verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ram', verbose_name='ОЗУ (GB)'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_diagonal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.screendiagonal', verbose_name='Диагональ экрана (дюймы)'),
        ),
    ]
