# Generated by Django 4.2.20 on 2025-05-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_batterycapacity_cameraspec_color_connectiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='12', max_length=50, unique=True, verbose_name='Камера (Мп)')),
            ],
        ),
        migrations.RemoveField(
            model_name='batterycapacity',
            name='capacity_mah',
        ),
        migrations.RemoveField(
            model_name='corecount',
            name='count',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='size_gb',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='size_gb',
        ),
        migrations.RemoveField(
            model_name='screendiagonal',
            name='size_inch',
        ),
        migrations.AddField(
            model_name='batterycapacity',
            name='value',
            field=models.CharField(default='5000', max_length=50, unique=True, verbose_name='Емкость аккумулятора (мАч)'),
        ),
        migrations.AddField(
            model_name='corecount',
            name='value',
            field=models.CharField(default='4', max_length=20, unique=True, verbose_name='Количество ядер'),
        ),
        migrations.AddField(
            model_name='memory',
            name='value',
            field=models.CharField(default='128', max_length=50, unique=True, verbose_name='Память (GB)'),
        ),
        migrations.AddField(
            model_name='ram',
            name='value',
            field=models.CharField(default='8', max_length=50, unique=True, verbose_name='ОЗУ (GB)'),
        ),
        migrations.AddField(
            model_name='screendiagonal',
            name='value',
            field=models.CharField(default='6.7', max_length=50, unique=True, verbose_name='Диагональ экрана (дюймы)'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(default='Черный', max_length=50, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='connectiontype',
            name='type',
            field=models.CharField(default='Беспроводные', max_length=50, unique=True, verbose_name='Тип подключения'),
        ),
        migrations.AlterField(
            model_name='connectortype',
            name='name',
            field=models.CharField(default='Type-C', max_length=100, unique=True, verbose_name='Разъем'),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='name',
            field=models.CharField(default='Не установлена', max_length=50, unique=True, verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='name',
            field=models.CharField(default='Intel core i5', max_length=100, unique=True, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='battery_capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.batterycapacity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='connection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.connectiontype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='connector_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.connectortype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='core_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.corecount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cpu_frequency',
            field=models.CharField(blank=True, default='2400', max_length=50, verbose_name='Частота процессора (Гц)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.memory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.operatingsystem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.processor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ram'),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_diagonal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.screendiagonal'),
        ),
        migrations.DeleteModel(
            name='CPUFrequency',
        ),
        migrations.AlterField(
            model_name='product',
            name='front_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_camera', to='accounts.camera'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_camera', to='accounts.camera'),
        ),
        migrations.DeleteModel(
            name='CameraSpec',
        ),
    ]
