# Generated by Django 4.2.20 on 2025-05-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_camera_remove_batterycapacity_capacity_mah_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='2400', max_length=100, unique=True, verbose_name='Частота процессора (Гц)')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='cpu_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cpufrequency'),
        ),
    ]
