# Generated by Django 4.2.20 on 2025-05-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_cpufrequency_alter_product_cpu_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectiontype',
            name='type',
        ),
        migrations.AddField(
            model_name='connectiontype',
            name='name',
            field=models.CharField(default='Беспроводные', max_length=100, unique=True, verbose_name='Тип подключения'),
        ),
    ]
