# Generated by Django 4.2.20 on 2025-05-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_connectiontype_type_connectiontype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectiontype',
            old_name='name',
            new_name='type',
        ),
    ]
