# Generated by Django 4.2.20 on 2025-05-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_name_connectiontype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontype',
            name='type',
            field=models.CharField(default='Беспроводные', max_length=50, unique=True, verbose_name='Тип подключения'),
        ),
    ]
