# Generated by Django 4.2.20 on 2025-05-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес ПВЗ'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='friday_close',
            field=models.TimeField(default='21:00:00', verbose_name='Пятница до'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='friday_open',
            field=models.TimeField(default='09:00:00', verbose_name='Пятница с'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='monday_close',
            field=models.TimeField(default='12:00:00', verbose_name='Понедельник до'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='monday_open',
            field=models.TimeField(default='09:00:00', verbose_name='Понедельник с'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название ПВЗ'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='saturday_close',
            field=models.TimeField(default='21:00:00', verbose_name='Суббота до'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='saturday_open',
            field=models.TimeField(default='09:00:00', verbose_name='Суббота с'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='sunday_close',
            field=models.TimeField(default='21:00:00', verbose_name='Воскресенье до'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='sunday_open',
            field=models.TimeField(default='09:00:00', verbose_name='Воскресенье с'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='thursday_close',
            field=models.TimeField(default='21:00:00', verbose_name='Четверг до'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='thursday_open',
            field=models.TimeField(default='09:00:00', verbose_name='Четверг с'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='tuesday_close',
            field=models.TimeField(default='21:00:00', verbose_name='Вторник до'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='tuesday_open',
            field=models.TimeField(default='09:00:00', verbose_name='Вторник с'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='wednesday_close',
            field=models.TimeField(default='21:00:00', verbose_name='Среда до'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='wednesday_open',
            field=models.TimeField(default='09:00:00', verbose_name='Среда с'),
        ),
        migrations.AlterField(
            model_name='product',
            name='battery_capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.batterycapacity', verbose_name='Емкость аккумулятора'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='connection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.connectiontype', verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='connector_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.connectortype', verbose_name='Разъем для подключения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='core_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.corecount', verbose_name='Количество ядер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cpu_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cpufrequency', verbose_name='Тактовая частота процессора'),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_camera', to='accounts.camera', verbose_name='Фронтальная камера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_camera', to='accounts.camera', verbose_name='Основная камера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.memory', verbose_name='Память'),
        ),
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.operatingsystem', verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.processor', verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ram', verbose_name='ОЗУ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_diagonal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.screendiagonal', verbose_name='Диагональ экрана'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Изображение профиля'),
        ),
    ]
